# Generated by ariadne-codegen on 2023-09-24 20:09
# Source: queries/

from typing import Any, Dict

from .base_client import BaseClient
from .get_program_project_list_by_project_id import GetProgramProjectListByProjectId


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def get_program_project_list_by_project_id(
        self, project_id: Any
    ) -> GetProgramProjectListByProjectId:
        query = gql(
            """
            query GetProgramProjectListByProjectId($projectId: uuid!) {
              project: projects_by_pk(id: $projectId) {
                program_project_list: program_projects(order_by: {program: {start_time: desc}}) {
                  program {
                    id
                    title
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"projectId": project_id}
        response = self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return GetProgramProjectListByProjectId.model_validate(data)
