# Generated by ariadne-codegen
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateGame(BaseModel):
    game: Optional["CreateGameGame"]


class CreateGameGame(BaseModel):
    id: Any


CreateGame.model_rebuild()
