# Generated by ariadne-codegen on 2023-10-17 18:26
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateProgramTwitterAnnouncementWithoutImage(BaseModel):
    program_twitter_announcement: Optional[
        "CreateProgramTwitterAnnouncementWithoutImageProgramTwitterAnnouncement"
    ]


class CreateProgramTwitterAnnouncementWithoutImageProgramTwitterAnnouncement(BaseModel):
    id: Any


CreateProgramTwitterAnnouncementWithoutImage.model_rebuild()
CreateProgramTwitterAnnouncementWithoutImageProgramTwitterAnnouncement.model_rebuild()
