# Generated by ariadne-codegen on 2023-10-02 11:55
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateGame(BaseModel):
    game: Optional["CreateGameGame"]


class CreateGameGame(BaseModel):
    id: Any


CreateGame.model_rebuild()
CreateGameGame.model_rebuild()
