# Generated by ariadne-codegen on 2023-10-17 18:26
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateProgram(BaseModel):
    program: Optional["CreateProgramProgram"]


class CreateProgramProgram(BaseModel):
    id: Any


CreateProgram.model_rebuild()
CreateProgramProgram.model_rebuild()
