# Generated by ariadne-codegen on 2023-10-17 18:26
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateProgramPerson(BaseModel):
    program_person: Optional["CreateProgramPersonProgramPerson"]


class CreateProgramPersonProgramPerson(BaseModel):
    id: Any


CreateProgramPerson.model_rebuild()
CreateProgramPersonProgramPerson.model_rebuild()
