# Generated by ariadne-codegen
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateTwitterTweetImage(BaseModel):
    twitter_tweet_image: Optional["CreateTwitterTweetImageTwitterTweetImage"]


class CreateTwitterTweetImageTwitterTweetImage(BaseModel):
    id: Any


CreateTwitterTweetImage.model_rebuild()
