# Generated by ariadne-codegen on 2023-10-02 11:55
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateProgramYoutubeVideoLiveArchive(BaseModel):
    program_live_archive: Optional[
        "CreateProgramYoutubeVideoLiveArchiveProgramLiveArchive"
    ]


class CreateProgramYoutubeVideoLiveArchiveProgramLiveArchive(BaseModel):
    id: Any


CreateProgramYoutubeVideoLiveArchive.model_rebuild()
CreateProgramYoutubeVideoLiveArchiveProgramLiveArchive.model_rebuild()
