# Generated by ariadne-codegen
# Source: queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateTwitterTweet(BaseModel):
    twitter_tweet: Optional["CreateTwitterTweetTwitterTweet"]


class CreateTwitterTweetTwitterTweet(BaseModel):
    id: Any


CreateTwitterTweet.model_rebuild()
