# Generated by ariadne-codegen
# Source: queries/

from typing import Any, List

from .base_model import BaseModel


class GetCreateProgramInitialData(BaseModel):
    project_list: List["GetCreateProgramInitialDataProjectList"]
    game_list: List["GetCreateProgramInitialDataGameList"]


class GetCreateProgramInitialDataProjectList(BaseModel):
    id: Any
    name: str


class GetCreateProgramInitialDataGameList(BaseModel):
    id: Any
    name: str


GetCreateProgramInitialData.model_rebuild()
