# Generated by ariadne-codegen
# Source: queries/

from typing import Any, List

from .base_model import BaseModel


class GetCreateProgramTwitterAnnouncementInitialData(BaseModel):
    project_list: List["GetCreateProgramTwitterAnnouncementInitialDataProjectList"]
    person_list: List["GetCreateProgramTwitterAnnouncementInitialDataPersonList"]
    twitter_account_list: List[
        "GetCreateProgramTwitterAnnouncementInitialDataTwitterAccountList"
    ]


class GetCreateProgramTwitterAnnouncementInitialDataProjectList(BaseModel):
    id: Any
    name: str


class GetCreateProgramTwitterAnnouncementInitialDataPersonList(BaseModel):
    id: Any
    name: str


class GetCreateProgramTwitterAnnouncementInitialDataTwitterAccountList(BaseModel):
    id: Any
    twitter_screen_name: str
    name: str


GetCreateProgramTwitterAnnouncementInitialData.model_rebuild()
