# Generated by ariadne-codegen on 2023-10-02 11:55
# Source: queries/

from typing import Any, List

from .base_model import BaseModel


class GetCreateProgramInitialData(BaseModel):
    project_list: List["GetCreateProgramInitialDataProjectList"]
    game_list: List["GetCreateProgramInitialDataGameList"]


class GetCreateProgramInitialDataProjectList(BaseModel):
    id: Any
    name: str


class GetCreateProgramInitialDataGameList(BaseModel):
    id: Any
    name: str


GetCreateProgramInitialData.model_rebuild()
GetCreateProgramInitialDataProjectList.model_rebuild()
GetCreateProgramInitialDataGameList.model_rebuild()
